### ISSUE TITLE
Understanding preview.zip in prs

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/collection-bioimage-io#727] opened 2024-03-01 09:37 UTC
I'm sorry if I didn't find the documentation for this, but I'd like to understand what I'm looking at with the `preview.zip` produced in a PR.

I'm not sure what I'm looking at when downloading the `preview.zip` from a PR. In particular, how are things ordered? Also it seems to use  the model names as folder names. Are model names unique? Otherwise there could be clashes. Ideally the preview would list the models by nickname? Easier to find and to remember?

**Comment by FynnBe** [comment] 2024-03-01 13:09
preview.zip was intended to show the new addition to the rdfs that would be deployed to gh-pages if the PR was merged.
Because of an issue on the main branch, it includes more than it should, but because this repo will soon be archived in favor of https://github.com/bioimage-io/collection I'm not investing time in fixing this

**Closed** 2024-03-01 13:09 UTC
